name: Multi-Stage Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-Nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t siva-web:Nginx .
          docker save siva-web:Nginx > image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  Test:
    runs-on: ubuntu-Nginx
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar

      - name: Test Docker image
        run: |
          docker run -d -p 8080:80 siva-web:Nginx
          sleep 5
          curl http://localhost:8080 | grep "IAM-SIVA-PRASAD"

  Push:
    runs-on: ubuntu-Nginx
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar

      - name: Tag and Push Docker image
        run: |
          docker tag siva-web:Nginx golisivaprasad/siva-web:Nginx
          docker push golisivaprasad/siva-web:Nginx

